### ISSUE TITLE
Missing (public) setter when dealing with Lists and Arrays.

### ISSUE THREAD

**Issue by Zicore** [mganss/XmlSchemaClassGenerator#9] opened 2015-08-11 13:27 UTC
It seems Arrays and Lists are generating no setters.
When I try to deserialize XML with Arrays and Lists, the objects are missing in the C# Model.

TypeClass.cs in Line 504:
`var isPrivateSetter = IsCollection || isArray;`
When I change it to `var isPrivateSetter = false;` deserialization works fine, because setters are generated.

**Comment by mganss** [comment] 2015-08-11 15:58
It's by design that the collection properties are read only:
https://msdn.microsoft.com/en-us/library/ms182327.aspx

However, when using .NET 4.0 and auto properties, this leads to this problem:
https://connect.microsoft.com/VisualStudio/feedback/details/528310/xmlserializer-fails-to-deserialize-readonly-members-that-are-collections-if-they-have-a-private-setter

But this should have been fixed in fe3d1e9b88f52ca8bff3bef048818eab594c8e7b (0.7). We're now always generating a backing field.

Which version are you using?
Can you provide a demo xsd/xml?

**Comment by Zicore** [comment] 2015-08-12 15:01
I downloaded the zip, like two days ago, so should be the recent version.

I can provide snippets of the generated code and the XSD:
```cs
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataBodyRequest> _body;
        
        /// <summary>
        /// <para>This element contains a message body</para>
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute("body", Namespace="***")]
        [System.Xml.Serialization.XmlArrayItemAttribute("request", Namespace="***"")]
        public System.Collections.ObjectModel.Collection<DataBodyRequest> Body
        {
            get
            {
                return this._body;
            }
        }
```
```xml
<xsd:element name="body" minOccurs="0" maxOccurs="1">
	<xsd:annotation>
		<xsd:documentation>This element contains a message body</xsd:documentation>
	</xsd:annotation>
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="request">
				<xsd:annotation>
					<xsd:documentation>A request specification</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="data">
							<xsd:annotation>
								<xsd:documentation>A request data</xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:sequence>
									<xsd:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="identifier" use="required">
						<xsd:annotation>
							<xsd:documentation>An unique request identifier, usually a data manager or workflow</xsd:documentation>
						</xsd:annotation>
						<xsd:simpleType>
							<xsd:restriction base="NVarChar">
								<xsd:minLength value="1" />
								<xsd:maxLength value="128" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
```

Body is empty when I deserialize my XML.

**Comment by mganss** [comment] 2015-08-12 16:59
It works for me with this XML:
```XML
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="http://tempuri.org/XMLSchema.xsd">
  <body>
    <request identifier="identifier1">
      <data />
    </request>
  </body>
</root>
```

But I think we shouldn't be generating a collection anyway for sequences whose single element has maxOccurs="1" (which is the default), "request" in this case.

Can you provide the XML (fragment) you're trying to deserialize?

**Closed** 2015-08-13 14:49 UTC
