### ISSUE TITLE
dotnet-xscgen incompatible with dotnet core 2.1

### ISSUE THREAD

**Issue by SierraNL** [mganss/XmlSchemaClassGenerator#73] opened 2018-06-26 11:36 UTC
I'm trying to use the dotnet cli tool in my project, but it's a dotnet core 2.1 project.
And I'm getting the following error:

> NU1202: Package dotnet-xscgen 2.0.106 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-xscgen 2.0.106 supports:
>   - net45 (.NETFramework,Version=v4.5) / any
>   - netcoreapp2.0 (.NETCoreApp,Version=v2.0) / any

Could you update the dependencies and push a new package?

I find it strange that a dotnet tool has a specific dependency with the project it's used in. Since they are actually independent.

**Comment by mganss** [comment] 2018-06-27 09:12
This is a duplicate of #71.

**Closed** 2018-06-28 15:30 UTC
Labels: duplicate
